version: "3.3"

networks:
  net:
    driver: bridge

services:
  postgres:
    image: postgres:15.1
    env_file: .env
    container_name: 'postgres-container'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 4G
    container_name: 'app-container'
    restart: unless-stopped
    hostname: server
    ports:
      - 8080:8080
    command: ./app
    depends_on:
      - postgres
    networks:
      - net

volumes:
  pg_data:
